print("CHARACTER - A")
print("    **")
print("   ** **")
print("  *******")
print(" **     **")
print("**       **")
print()
print()
print("A Flying Bird")
print("-            -")
print("  \\        / ")
print("   \\  ..  /  ")
print("      \\/    ")
print()
print("CHARACTER - E")
print("#########")
print("#########")
print("##")
print("##")
print("######")
print("######")
print("##")
print("##")
print("#########")
print("#########")